name: Deploy React App
on: push
jobs:
  testDep:
    runs-on: ubuntu-latest
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
  lint:
    runs-on: ubuntu-latest
    needs: testDep
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Lint App
        run: npm run lint
  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Get the repository code
        uses: actions/checkout@v3
      - name: Install dependecies
        run: npm install
      - name: Deploy
        run: echo Deploying ...
