
name: wallet workflow
on: workflow_dispatch
jobs: 
   wallet:
      runs-on: ubuntu-latest
      steps: 
       - name: Print to console  
         run: echo Hello  
        - name: Print a few lines
        run: 
        echo First lines
        echo Second
